system:
  random_seed: 1
  mindspore_seed: 1
  numpy_seed: 1
  context_mode: "graph_mode"
  graph_kernel_flags: null


dataset:
  dataset_name: "cbsd68"
  input_path: "/data/LLVT/NoahTCV/data/CBSD68"
  eval_batch_size: 1
  num_frames: 0
  scale: 1
  noise_level: 50
  dataset_sink_mode: False
  num_parallel_workers: 8


model:
  name: "NOAHTCV"
  load_path: "/data/LLVT/NoahTCV/ckpt/best_gpu.ckpt"


loss:
  name: "MSELoss"
  loss_scale: 1.0
  amp_level: "O0"

scheduler:
  base_lr: 0.00001
  min_lr: 1e-08
#  name: "warmup_cosine_decay"
#  name: "cosine_decay"
  name: "cosine_annealing"

  weight_decay: 0
  warmup_epochs: 0
  warmup_factor: 1.0

# Optimizer options
optimizer:
  name: "Adam"
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999


# Metric options
metric:
  PSNR:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null
  SSIM:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null

test_pipeline:
  name: "noahtcv"
  pipeline: null
